### ISSUE TITLE
convert internal communication to gRPC

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#157]
gRPC has benefits over REST especially in service-to-service communication

the Safe API can be converted from REST to gRPC.

Notes:
* this is a breaking change for workloads, unless we also keep the REST API for workloads intact — need to discuss that.

**Comment by krishnaduttPanchagnula** [comment]
are we planning to do this @v0lkan ?

**Comment by v0lkan** [comment]
Hey @krishnaduttPanchagnula; 

Yes, that is in our mid-to-long-term goals.

It's not a high priority in the grand scheme of things, but we’ll get there.

Do you feel like it is a good move, or keeping it RESTful might have benefits?

**Comment by v0lkan** [comment]
@krishnaduttPanchagnula on a second though; I think it’s better to keep things RESTful.

We will have other external SDKs (for Python, Java, and C, etc) and we will have a guide for external SDK developers (as per @RamXX ’s recommendation)

REST is easier to interact and develop a SDK aroudn, whereas dealing with gRPC will be relatively harder.

I’m proposing to keep things simpler, and keep the inner APIs RESTful as an architectural decision.

If there is an ask from the community to have a gRPC API too, then we can think about it;
but even when we do that, it would make sense to keep the REST API for backwards compatibility.

I’m closing this issue for now; we can re-open if we decide otherwise.

--
cc: @abhishek44sharma @ats0stv (too keep you folks in the loop)
