### ISSUE TITLE
provide more keywords in the charts.yaml

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#172]
The only keywords we have is `secrets`

```
keywords:
  - secrets
```

better to add more.

[kubernetes](https://github.com/topics/kubernetes)  [security](https://github.com/topics/security) [secret-management](https://github.com/topics/secret-management)  [edge](https://github.com/topics/edge)  [cloud-native](https://github.com/topics/cloud-native) [zero-trust](https://github.com/topics/zero-trust)  [spiffe](https://github.com/topics/spiffe)  [spire](https://github.com/topics/spire) [secrets-manager](https://github.com/topics/secrets-manager)

^ these are what we have in the repo, for starters.

**Comment by v0lkan** [comment]
Waiting for #178 to be merged to close this one.

**Comment by abhishek44sharma** [comment]
@krishnaduttPanchagnula are you working on this?

**Comment by krishnaduttPanchagnula** [comment]
> @krishnaduttPanchagnula are you working on this?

I have complete in pr #178

**Comment by abhishek44sharma** [comment]
> > @krishnaduttPanchagnula are you working on this?
> 
> I have completed this in pr #178, previously but @abhishek44sharma you mentioned that to be done in chart 0.21.1

Yes and 0.21.0 is initialized [here](https://github.com/vmware-tanzu/secrets-manager/tree/main/helm-charts/0.21.0). Ready for development, if you wanna create PR.

**Comment by krishnaduttPanchagnula** [comment]
> > > @krishnaduttPanchagnula are you working on this?
> > 
> > I have completed this in pr #178, previously but @abhishek44sharma you mentioned that to be done in chart 0.21.1
> 
> Yes and 0.21.0 is initialized [here](https://github.com/vmware-tanzu/secrets-manager/tree/main/helm-charts/0.21.0). Ready for development, if you wanna create PR.

Will push raise pr tomorrow

**Comment by abhishek44sharma** [comment]
> Updated this issue on Pr #236 . @abhishek44sharma

Thanks @krishnaduttPanchagnula 👍
