### ISSUE TITLE
create a template for the blog

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#176]
we have a poor man’s blog here; maintained under source control

https://vsecm.com/blog/keep-your-secrets/

however, it does not feel like a blog aritcle, it needs some UI work; such as removing the left hand navigation and providing a more blog-like navigation without losing the overall monotype feel of the site to keep things consistent.

**Comment by abhishek44sharma** [comment]
Make-do fix done by #231
