### ISSUE TITLE
In the makefile help, instead of sayig “Istanbul”; saying “Distroless” makes more sense.

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#217]
“Istanbul” is an internal jargon / codename. Whereas “distroless” is known by the industry. Better to replace “Istanbul”s in the help message to distroless

“Istanbul Images” » “Distroless Images”

“Istanbul FIPS Images » “Distroless FIPS Images”

**Comment by gantanikhilraj** [comment]
hey @v0lkan , I would like to work on this, please assign me.

**Comment by v0lkan** [comment]
It’s yours Nikhil; enjoy :)

**Comment by v0lkan** [comment]
Heads up; I am doing a docs overhaul. 

One of my PRs may inadvertently fix this.

**Comment by gantanikhilraj** [comment]
ok @v0lkan, I will take up another issue.

**Comment by v0lkan** [comment]
Closing this one. — Today’s changes already fixed it.
