### ISSUE TITLE
website: move changelog, releases, and roadmap all the way to the bottom so that they don’t get in the way of the reader’s flow

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#233]
they are relatively less important for someone who’s learning the tool, so it makes sense to put them at the section down below

order woudl be

Maintainers
Security
VSecm Blog
(divider)
Preface
What is VSecM

…

(divider)
Changelog 
Releases
Roadmap
(divider)
Release Management
Governance
Privacy Policy

**Comment by abhishek44sharma** [comment]
Fixed by #234
