### ISSUE TITLE
Quickstart should include a way to install vsecm via helm

### ISSUE THREAD

**Issue by farhan-pasha** [vmware-tanzu/secrets-manager#241]
The [Quickstart Guide](https://vsecm.com/docs/quickstart/) should include **ANY** of the following, demonstrating a way to install vsecm using helm chart:

- a link for helm chart based installation
- a sub section for helm chart based installation
- separate tabs for normal(make) and helm chart based installation in the installation sub-section

**Comment by v0lkan** [comment]
Done.
