### ISSUE TITLE
`safe -l` is not displaying the record updated and record created (it displays empty jsons instead)

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#307]
```
🐢⚡️↪vsecm-001↪inspector↪k exec $SENTINEL -n vsecm-system -- safe -l

{"secrets":[{"name":"example","created":{},"updated":{}}]}
```

This is probably a regression.

My guesstimate is that the dates are set but not rendered due to some parsing issue.

If the dates are not set, it might require more investigation.

Whenever a secrets is created it gets a "created" timestamp; and whenever a secret is updated it has an "updated" timpestamp)

**Comment by puskuruk** [comment]
I'd like to work this issue.

**Comment by v0lkan** [comment]
@puskuruk assigned it to you.

**Comment by v0lkan** [comment]
How I would start looking at the issue:

Here, the API prepares a response (app/safe/internal/route/list.go)

```go
	log.DebugLn(&cid, "List: before response")

	_, err = io.WriteString(w, string(resp))
	if err != nil {
		log.InfoLn(&cid, "List: Problem sending response", err.Error())
	}

	log.DebugLn(&cid, "List: after response")
```

there you can temporarily modify the code to see if the timestamps are indeed there:

```go
	log.DebugLn(&cid, "List: before response")
	
	// range over secret sfr.Secrets
	for _, secret := range sfr.Secrets {
		fmt.Println(secret.Created)
		fmt.Println(secret.Updated)
	}
```

If they are there, then the problem is the way they are serialized;
If not, the problem is that they are not being set for some reason.

Good luck.

**Comment by v0lkan** [comment]
FIXED.
