### ISSUE TITLE
Update the links for `edit this page on GitHub` in docs

### ISSUE THREAD

**Issue by farhan-pasha** [vmware-tanzu/secrets-manager#331]
As noticed by @huseyingulec in https://github.com/vmware-tanzu/secrets-manager/issues/328, there are some doc pages which requires updated links for `edit this page on GitHub` .

Few example noted: 

- https://vsecm.com/docs/contact/
- https://vsecm.com/docs/changelog/
- https://vsecm.com/docs/releases/

Action required:
- Identify pages that requires such updates.
- Fix them and create a PR.

ScreenShots:

<img width="1486" alt="Screenshot 2023-11-11 at 23 55 34" src="https://github.com/vmware-tanzu/secrets-manager/assets/36415062/afb944d0-650b-402f-a950-7f58932c9c9b">
<img width="1235" alt="Screenshot 2023-11-11 at 23 57 25" src="https://github.com/vmware-tanzu/secrets-manager/assets/36415062/885a4430-4ea6-4867-a799-f8b0426cc50c">

**Comment by huseyingulec** [comment]
I'd like to solve this issue.
