### ISSUE TITLE
save test coverages in the repo

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#396]
when merging code, the code coverage shall be updated and merged with the code.

we can have a helper script for that maybe.

**Comment by marikann** [comment]
Firstly i want to add coverage badge. When main branches get to new codes, this badge will be updated.

I will use this repo for this work; https://github.com/ncruces/go-coverage-report

It's good choice cause when we click coverage badge it go to coverage.html

I added screen shots.



![Ekran görüntüsü 2024-02-24 222736](https://github.com/vmware-tanzu/secrets-manager/assets/79652547/de2a9a4f-10f8-403c-a9ac-e86c4ab194ce)
![Ekran görüntüsü 2024-02-24 222758](https://github.com/vmware-tanzu/secrets-manager/assets/79652547/81fdfa5b-86b7-4f01-b75d-1ee3138f41fd)


If this okay for you, you can assigne to me.

**Comment by v0lkan** [comment]
It looks good to me; assigned. 

Have fun 🚀 .

**Comment by marikann** [comment]
plus;

https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions

From this article I understand that we have 2000 minutes per month.

I think you'd want to check this out.

But other vmware's repositories use github actions.

**Comment by v0lkan** [comment]
Thanks for the reference.

That should be okay, I think.

**Comment by v0lkan** [comment]
Closing this one since the reports are there.
