### ISSUE TITLE
random secret generator needs unit tests

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#397]
We have a secret genereation code.

Due to its isolated nature, it’s relatively easy to write tests around it.
Yet there are no tests.

Test secret generation capabilities of VSecM.

The secret generator code is here:
https://github.com/vmware-tanzu/secrets-manager/blob/main/core/crypto/value.go ( GenerateValue )

**Comment by muratmirgun** [comment]
Can I take this issue?

**Comment by v0lkan** [comment]
Of course you can :)

**Comment by v0lkan** [comment]
@muratmirgun are you done with this one? can I close it?

**Comment by v0lkan** [comment]
Closing this since we already have tests there.

@muratmirgun if you believe it needs to be reopened, please let me know.
