### ISSUE TITLE
Create a `Service` around VSecm Sentinel

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#404]
This will be optional. 

Ideally, the only way to talk to VSecm Safe shall be through VSecm Sentinel to limit the attack surface.

However, if a client has a valid SVID that VSecm Safe knows and approves of, it should be able to consume its restful API.

The problem here is: as an end-user, I might not be able to do mTLS (assume you are using a web admin console that talks to VSecM Safe), so we might need to put something like a Oauth, or OIDC, or Keycloak, or some similar form of authentication. 

We can provide a sample service but securing the service shall be the responsibility of the operator.

The important thing is, whoever authenticates to that service will have full access to VSecM Safe, so it’s VERY important to have a secure design, even if it is a starting recommendation that the user might want to improve upon.

**Comment by sahinakyol** [comment]
Could you assign to me @v0lkan ?

**Comment by v0lkan** [comment]
Assigning, but let’s talk about this too — I haven’t thought about the security implications of it a lot.

We can sync over discord again.

**Comment by v0lkan** [comment]
@sahinakyol, this feature will be a great learning experience for you, but we definitely need to collaborate. — Thanks for wanting to start working on this valuable issue.

@abhishek44sharma @farhan-pasha, @st96d045, @ats0stv, @RamXX, and anyone interested: 
I’ll create a Slack channel and maybe a Zoom session to discuss the architectural needs.

For now, here’s my brain dump.

## Overview

By design, only a human operator (like a cluster admin) can access VSecM Sentinel. This is important wrt security because it’s the access point to the entire kingdom.

This user request presents a classic security versus convenience dilemma.
As a solution, we should be secure by default. While giving the user the privileges, we need to CLEARLY express what kind of risk they are taking, how they should limit this access to a single workload/service, and what they would need to do to secure that workload.

## Risk Assessment

### Current System

Our existing system with SPIFFE ID limitations ensures that only specific workloads can access certain secrets, significantly reducing the risk of unauthorized access.


### Proposed Change

Introducing a service that allows assigning any secret to any workload increases convenience but significantly elevates the risk of unauthorized access through misconfiguration or malicious activities.

### Potential Solution

Create a SPIFFE ID with Global Access and assign it to the workload that needs a global access. This ID should have the stringest access control because inadvertently copy/pasting it to a workload that is not meant to, will mean giving a workload superadmin access.

However, `ClusterSPIFFEID`’s are cluster-level CRDs, and we should assume that a cluster admin would be sane enough to not spread a global clusterspiffeid like candies on Halloween.

But still, we should clarify this everywhere: in documentation, in the naming convention used for the ID (something like `spiffe://$trustRoot/w/$workloadName/__$$DANGEROUSLY_ENABLE_GLOBAL_ACCESS$$__` or something similar. It should look risky, it should look ugly, and if someone creates that SPIFFE ID, they should at least be tempted to RTFM.

We should add additional authentication layer (at least on the use case examples we create — like OAuth2.0 or OIDC — we can use Keycloak as an identity provider for our examples, if we don’t want to create an IDP from scratch. idp is not VSecm’s job; but having an IDP integration for this use case is a a must, so we can use Keycloak and document this as an option)

In addition, we should have tight network policies around our sample workload in the example use case that will have global access.

Plus, we should have audit trails; or at least mention that in a production setup any sane user shall have audit trails.

Also we can decleratively limit the capability, as in: have a configmap and opt in for access to workload, the person who creates the clusterspiffeid shall also create a `ConfigMap` in `vsecm-system` namespace and explicitly define what global access means.

While this means, we are essentially defining policies; and policy-based access control is ideally out of scope of this project; demanding such a ConfigMap change will prevent any inadvertent assignment of global access to unwanted workloads.

We should clearly document this, in an understandable fashion, highlighting risks and mitigation that need to be taking to eliminate those risks. Also asking (maybe begging) the use to assess their security needs, and reconsider whether they really need this feature (there might be valid reasons, like they might have an OIDC-secured Service Management and Orchestration control plane and they might want to use this feature as a “plug in” to their control plane that only admins etc can access anyway) — But still, sometimes what use wants might be different than what the user needs; and sometimes what the user want might not align with security best practices.

We should have an action plan for abuse and misuse: Even with the strictest policies, there is a possibility for the feature to be abused, due to things like time pressure, deadlines, or simply not understanding the risks. Clearly document the necessity of having an incident  response plan in place for that.

---

Those are what I can think of initially.
Take this as a high-level, non-normative overview.

I’ll come of with a more nerdy/architectural design doc sometime when I can find time to wrap my head around, and I’ll present it to the interested parties.

Cheers,

V.

**Comment by v0lkan** [comment]
Merged. Closing.
