### ISSUE TITLE
create a Java SDK

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#448]
We have a Golang SDK that exposes two methods and uses [go-spiffe][go-spiffe] as a library:

* [`func Fetch() (reqres.SecretFetchResponse, error)`][fetch]
* [`func Watch()`][watch]

The task here is to 

1. Write Java equivalents of these methods.
2. Use [java-spiffe][java-spiffe] instead of [go-spiffe][go-spiffe].
3. Create a sample Java application that uses this SDK.
4. Dockerize the app to be pushed to the vsecm container registry like other sample apps.
5. Create unit tests
6. create documentation for the vsecm website
7. and the like…

[watch]: https://github.com/vmware-tanzu/secrets-manager/blob/main/sdk/sentry/watch.go
[fetch]: https://github.com/vmware-tanzu/secrets-manager/blob/main/sdk/sentry/fetch.go
[go-spiffe]: https://github.com/spiffe/go-spiffe
[java-spiffe]: https://github.com/spiffe/java-spiffe

We can create a `./sdk-java` folder in the project root for this.

**Comment by sahinakyol** [comment]
Hello, can I take this issue?

**Comment by emincanoguz11** [comment]
Also i can take this issue for helping @sahinakyol

**Comment by v0lkan** [comment]
Assigned to both of you folks — thanks a lot.

I’ll share some details here.

**Comment by v0lkan** [comment]
https://github.com/spiffe/java-spiffe

+ coordinate with Patrick (Qi Hu) on VSecM Slack workspace.
