### ISSUE TITLE
consider creating a C/C++ SDK

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#450]
To keep things simpler we can compile the golang SDK as an embeddable module that a C/C++ environment can use, and create some wrappers around it maybe.

**Comment by yigithankarabulut** [comment]
Could you assign to me, I want to try it @v0lkan

**Comment by v0lkan** [comment]
Assigned.

I’ll add more details sometime this week, hopefully.

**Comment by v0lkan** [comment]
reassigned :)

**Comment by v0lkan** [comment]
The idea is to reutilize the go code by using a module in the c code.

But we can also explore using https://github.com/HewlettPackard/c-spiffe
