### ISSUE TITLE
saving root key via VSecM Safe in manual mode should optionally update the internal k8s secret too

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#460]
When in manual_input mode, adding the root key to VSecM Safe via VSecM sentinel does not create a k8s secret.

That is the default (and safer) behavior.

However, that behaviour should be able to be overridden with an environment variable settings.

If that environment variable is set, then saving to root key should also update the internal k8s secret.

**Comment by v0lkan** [comment]
Assigned. Enjoy.

**Comment by v0lkan** [comment]
I’ll add some more details here; maybe a sequence diagram of how things work, and how it ought to have been.

**Comment by v0lkan** [comment]
Hey @gurkanguray what’s the status of this?

**Comment by gurkanguray** [comment]
Hi @v0lkan, I’m going to create a new pull request today. There were so many conflicts since I couldn't work on the task for a while. Therefore, I’m working on a new pull request 👍

**Comment by v0lkan** [comment]
👍 .

**Comment by v0lkan** [comment]
Closing this.

We need to write an integration test around this of course.
