### ISSUE TITLE
change copyright statements to align with other VMware projects

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#487]
Since there is no more VMware, Inc., the copyright shall reflect that.

I checked a few VMware open source projects and they have a pattern similar to this:

```text
// Copyright 2020-2022 the Pinniped contributors. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
```

By that token, we shall change our copyright haeders into this:

```text
# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets… secret
# >/
# <>/' Copyright 2023–present VMware Secrets Manager contributors.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */
```

**Comment by v0lkan** [comment]
That is, replace `VMware, Inc.` with `VMware Secrets Manager contributors` across the project.

**Comment by v0lkan** [comment]
All yours. Thank you for saving us a massive find and replace chore :D .

**Comment by huseyingulec** [comment]
I see, my Prettier extension is changed everything :( . It should be fine with new commits.
