### ISSUE TITLE
create a Python SDK

### ISSUE THREAD

**Issue by emincanoguz11** [vmware-tanzu/secrets-manager#505]
Python developers' need for Python SDK to implementing code. So that I create issue for this reason. 

To-Do

- [ ] Check the project and planned codebase SDK for checking project.
- [ ] Write Python scripts and also write unit tests.
- [ ] Check code standards including in PyLint
- [ ] Write Dockerfile and check versions of Python

**Comment by v0lkan** [comment]
Hey @emincanoguz11 ; thanks for looking into this. I’ll share some details in the comments when I find some time.

a VSecM Python SDK can indeed be a useful addition to the project.

**Comment by v0lkan** [comment]
https://github.com/HewlettPackard/py-spiffe
