### ISSUE TITLE
Sentinel logging: we migh want to introduce log levels, similar to the ones used on VSecM Safe

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#517]

**Comment by v0lkan** [comment]
Marking it “low priority” because Sentinel is not as heavily used as other system components.

While introducing log levels, we shall also introduce audit logs — audit logs will not be suppressed regardless of the current log level.

Similar to Safe, we should use the `VSECM_LOG_LEVEL` environment variable to configure the log level.

**Comment by sahinakyol** [comment]
@v0lkan Could you assign to me?

**Comment by v0lkan** [comment]
I think this is done; closing it.

Let me know if we need to reopen.
