### ISSUE TITLE
create a Rust SDK

### ISSUE THREAD

**Issue by ghost** [vmware-tanzu/secrets-manager#556]
Hello maintainers,

I am interested in creating a Rust SDK for VMware Secrets Manager to improve support for Rust developers on this platform. I would appreciate your assistance and suggestions on the next steps to take. Thank you!

**Comment by v0lkan** [comment]
Luckily, SPIFFE has a rust crate:

https://github.com/maxlambrecht/rust-spiffe

We might leverage that.

We have two methods in the Go SDK; `Fetch` and `Watch`.

Our goal would be to create similar logic in Rust while preserving behavior parity.

**Comment by parlakisik** [comment]
I can work on that

**Comment by v0lkan** [comment]
Thanks a lot @parlakisik for working on this.

Here's the current Go SDK: https://github.com/vmware-tanzu/secrets-manager/tree/main/sdk

The public methods of the SDK are:

* `sentry.Watch()`: https://github.com/vmware-tanzu/secrets-manager/blob/main/sdk/sentry/watch.go#L25
* `sentry.Fetch()`: https://github.com/vmware-tanzu/secrets-manager/blob/main/sdk/sentry/fetch.go#L44
* `startup.Watch()`: https://github.com/vmware-tanzu/secrets-manager/blob/main/sdk/startup/watch.go#L28

The Go SDK leverages `go-spiffe` ( https://github.com/spiffe/go-spiffe )

There is a similar Rust create ( https://github.com/maxlambrecht/rust-spiffe ) that we can leverage.

Feel free to ping me offline for details.

May the source be with you.
