### ISSUE TITLE
SPIIRE 1.9.1 is out; we need helm charts update

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#600]

**Comment by v0lkan** [comment]
Hey @abhishek44sharma is this one done?

**Comment by abhishek44sharma** [comment]
No @v0lkan, last time I had upgraded to 1.9.0.
Will close it today.

**Comment by abhishek44sharma** [comment]
But I can see 23.3 points to 1.9.1. So yes we can close this issue.

**Comment by v0lkan** [comment]
Closing then :).
