### ISSUE TITLE
vsecm shall watch the secrets that it manages

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#705]
If someone updates/deletes the a secret that vsecm is managing, vsecm shall revert the change.

**Comment by sahinakyol** [comment]
Could you assign to me @v0lkan ?

**Comment by v0lkan** [comment]
I want to sleep on it a bit :) 

Let me think of the best way to do this architecturally, and then assign that to you :)

**Comment by v0lkan** [comment]
I am marking this as “pending” until we reach 50% code coverage.
