### ISSUE TITLE
a cli to check if a secret exists (like, return true/false based on if there is an assigned secret to a workload

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#706]

**Comment by sahinakyol** [comment]
Could you assign to me @v0lkan ?

**Comment by v0lkan** [comment]
Assigned. 

We can discuss the details separately.

**Comment by v0lkan** [comment]
I am marking this as “pending” until we reach 50% code coverage.

**Comment by v0lkan** [comment]
I think it’ll be something like

```
safe -w $workloadName -l
```

which will be a subset of `safe -l` and instead of listing everything, it will just list the secret for that workload or something empty if there is no secret.
