### ISSUE TITLE
think about a way to securely share root key material across vsecm instances in different clusters

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#707]

**Comment by sahinakyol** [comment]
Could you assign to me @v0lkan ?

**Comment by v0lkan** [comment]
will think about that too :)

**Comment by v0lkan** [comment]
I am marking this as “pending” until we reach 50% code coverage.

**Comment by v0lkan** [comment]
WONTFIX:

We do't need to share root key; we can have a relay mechanism to encrypt and share secrets over instead, and each VSecM can still use their own root key to store the secrets.
