### ISSUE TITLE
Publish Stats() as prometheus metrics

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#711]

**Comment by sahinakyol** [comment]
Could you assign to me @v0lkan ?

**Comment by v0lkan** [comment]
I am marking this as “pending” until we reach 50% code coverage.

**Comment by v0lkan** [comment]
Closing. 

Not much happening in VSecM Safe; it’s not that metrics-worthy.

If there is a community request, we can reconsider.
