### ISSUE TITLE
Update Quickstart Instructions to Use Helm Install Instead of Make Deploy

### ISSUE THREAD

**Issue by marikann** [vmware-tanzu/secrets-manager#743]
The current Quickstart instructions for this project use the make deploy command, which seems to be causing issues as it relies on the upcoming version. This has resulted in the command not functioning as expected. To resolve this, I propose updating the Quickstart instructions to use the helm install vsecm vsecm/vsecm command instead. This change will ensure that the instructions are accurate and up-to-date, leading to a smoother setup process for users.

![Screenshot_20240325_180916](https://github.com/vmware-tanzu/secrets-manager/assets/79652547/e3aeebd0-106b-45cb-82a5-e798c736a4d6)

**Comment by v0lkan** [comment]
Done. 

Thaks for reporting this ❤️ .
