### ISSUE TITLE
we need unit tests and coverage reports

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#78]

**Comment by v0lkan** [comment]
We have unit tests; but we still don’t have coverage reports.

**Comment by abhishek44sharma** [comment]
@v0lkan with https://github.com/vmware-tanzu/secrets-manager/pull/377 MR merged, it will show coverage as below:
`ok      github.com/vmware-tanzu/secrets-manager/core/log        0.300s  coverage: 13.8% of statements
ok      github.com/vmware-tanzu/secrets-manager/core/probe      (cached)        coverage: 12.5% of statements
ok      github.com/vmware-tanzu/secrets-manager/core/template   (cached)        coverage: 90.0% of statements
ok      github.com/vmware-tanzu/secrets-manager/core/validation (cached)        coverage: 100.0% of statements`
If this coverage is enough then we can close #78 now.

**Comment by v0lkan** [comment]
Yup. we can close this one.

We need a place to save those coverage reports, but that can be a separate feature.
