### ISSUE TITLE
Store Generated Proto Files in the Repo

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#828]
Why?

1. Immediate Buildability: Including generated files in the repository ensures that anyone who clones the repo can build the project immediately without additional steps.
2, Simplified Build Process: No need for contributors to set up and run the protoc compiler as a prerequisite for building the project. This can be especially beneficial in environments where dev don’t need to set up extra tooling just to contribute to the project.
3. Consistency: Storing the generated files in the repo ensures that every developer is using the exact same version of generated code, reducing discrepancies between environments.

The obvious cons are:
1. repository bloat.
2. possible merge conflicts.
3. redundancy.

I believe the pros of this approach outweigh the cons. Especially because we don’t have that many proto files, and the proto files do not change that much.

**Comment by v0lkan** [comment]
Once done, we should update the docs too.

**Comment by marikann** [comment]
Can you assign to me ?

**Comment by v0lkan** [comment]
All yours, enjoy :) .

**Comment by v0lkan** [comment]
Closing this as it is done.
