### ISSUE TITLE
There MUST be no unpatched vulnerabilities of medium or higher severity that have been publicly known for more than 60 days.

### ISSUE THREAD

**Issue by v0lkan** [vmware-tanzu/secrets-manager#88]
The vulnerability must be patched and released by the project itself (patches may be developed elsewhere). A vulnerability becomes publicly known (for this purpose) once it has a CVE with publicly released non-paywalled information (reported, for example, in the [National Vulnerability Database](https://nvd.nist.gov/)) or when the project has been informed and the information has been released to the public (possibly by the project). A vulnerability is considered medium or higher severity if its [Common Vulnerability Scoring System (CVSS)](https://www.first.org/cvss/) base qualitative score is medium or higher. In CVSS versions 2.0 through 3.1, this is equivalent to a CVSS score of 4.0 or higher. Projects may use the CVSS score as published in a widely-used vulnerability database (such as the [National Vulnerability Database](https://nvd.nist.gov/)) using the most-recent version of CVSS reported in that database. Projects may instead calculate the severity themselves using the latest version of [CVSS](https://www.first.org/cvss/) at the time of the vulnerability disclosure, if the calculation inputs are publicly revealed once the vulnerability is publicly known. Note: this means that users might be left vulnerable to all attackers worldwide for up to 60 days. This criterion is often much easier to meet than what Google recommends in [Rebooting responsible disclosure](https://security.googleblog.com/2010/07/rebooting-responsible-disclosure-focus.html), because Google recommends that the 60-day period start when the project is notified even if the report is not public. Also note that this badge criterion, like other criteria, applies to the individual project. Some projects are part of larger umbrella organizations or larger projects, possibly in multiple layers, and many projects feed their results to other organizations and projects as part of a potentially-complex supply chain. An individual project often cannot control the rest, but an individual project can work to release a vulnerability patch in a timely way. Therefore, we focus solely on the individual project's response time. Once a patch is available from the individual project, others can determine how to deal with the patch (e.g., they can update to the newer version or they can apply just the patch as a cherry-picked solution).

**Comment by pandatix** [comment]
Hey, SIG CVSS member and maintainer of [github.com/pandatix/go-cvss](https://github.com/pandatix/go-cvss) here.
Notice the CVSS v2 specification does not provide the rating feature from CVSS v3.0 and v3.1 (will be in CVSS v4.0 too).

This rating concept comes from the NVD.

**Comment by v0lkan** [comment]
That’s fine :) — and also thanks for the extra info ;) .

**Comment by v0lkan** [comment]
Closing this, as we updated our security policy: https://vsecm.com/docs/security/

We will target a 60-day time frame and prioritize those vulns above other features and bugs.
